apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: iaasadmin.in/develop/sa-frontend:1.0.0 
      name: sa-frontend
      ports:
        - containerPort: 80
