apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 # 2
spec:                                                # 3
  imagePullSecrets:
    - name: harbor-registry-secret
  containers:
    - image: iaasadmin.in/develop/sa-frontend:1.0.0 # 4
      name: sa-frontend                              # 5
      ports:
        - containerPort: 80                          # 6
