apiVersion: v1
kind: Service
metadata:
  name: sa-logic
spec:
  imagePullSecrets:
    - name: harbor-registry-secret
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: sa-logic
